"""
export_service.py — Generate Markdown and PDF security reports from scan data.

Supports two output formats:
  - generate_markdown(scan) → str
  - generate_pdf(scan)      → bytes
"""

from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from typing import Any

from fpdf import FPDF

logger = logging.getLogger(__name__)

_FOOTER_TEXT = "Generated by BreakMyApp • breakmyapp-production-2f29.up.railway.app"

# ---------------------------------------------------------------------------
# Severity colour helpers (used by both renderers)
# ---------------------------------------------------------------------------

_SEVERITY_COLORS: dict[str, tuple[int, int, int]] = {
    "CRITICAL": (220, 38, 38),
    "HIGH": (234, 88, 12),
    "MEDIUM": (202, 138, 4),
    "LOW": (22, 163, 74),
    "INFO": (100, 100, 100),
}


def _severity_color(severity: str) -> tuple[int, int, int]:
    return _SEVERITY_COLORS.get((severity or "").upper(), (100, 100, 100))


def _score_color(score: int | None) -> tuple[int, int, int]:
    if score is None:
        return (100, 100, 100)
    if score >= 80:
        return (22, 163, 74)   # green
    if score >= 60:
        return (202, 138, 4)   # amber
    return (220, 38, 38)       # red


def _trunc(text: str, max_len: int) -> str:
    """Truncate *text* to *max_len* characters, appending '...' if needed."""
    if not text:
        return ""
    s = str(text)
    return s if len(s) <= max_len else s[: max_len - 3] + "..."


# ---------------------------------------------------------------------------
# Markdown generator
# ---------------------------------------------------------------------------

def generate_markdown(scan: Any) -> str:
    """Return a complete Markdown security report for *scan*."""

    findings: dict = (scan.findings or {}) if scan.findings is not None else {}
    ai: dict = findings.get("ai_explanation") or {}
    cat_exp: dict = ai.get("category_summaries") or {}
    top_priorities: list = ai.get("top_priorities") or []
    positive_findings: list = ai.get("positive_findings") or []

    score = scan.score
    score_str = f"{score}/100" if score is not None else "N/A"
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # 1. Title
    lines.append("# BreakMyApp Security Report\n")

    # 2. Metadata table
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Repository | {scan.repo_url or 'N/A'} |")
    lines.append(f"| Scan ID | {scan.id} |")
    lines.append(f"| Score | {score_str} |")
    lines.append(f"| Status | {scan.status or 'N/A'} |")
    lines.append(f"| Generated At | {generated_at} |")
    lines.append("")

    # 3. Executive Summary
    lines.append("## Executive Summary\n")
    lines.append(ai.get("executive_summary") or "_No executive summary available._")
    lines.append("")

    # 4. Production Readiness Score
    lines.append("## Production Readiness Score\n")
    lines.append(f"**{score_str}**")
    lines.append("")
    lines.append(ai.get("score_explanation") or "_No score explanation available._")
    lines.append("")

    # 5. Top Priorities
    lines.append("## Top Priorities\n")
    if top_priorities:
        for i, priority in enumerate(top_priorities, 1):
            title = priority.get("title") or "Untitled"
            severity = priority.get("severity") or "INFO"
            description = priority.get("explanation") or ""
            recommendation = priority.get("action") or ""

            lines.append(f"{i}. ### {title}")
            lines.append(f"   **Severity:** `{severity}`")
            if description:
                lines.append(f"   {description}")
            if recommendation:
                lines.append(f"   **Recommendation:** {recommendation}")
            lines.append("")
    else:
        lines.append("_No top priorities identified._")
        lines.append("")

    # 6. Findings by Category
    lines.append("## Findings by Category\n")

    # 6a. Secrets Detection
    lines.append("### Secrets Detection\n")
    secrets_exp = cat_exp.get("secrets") or ""
    if secrets_exp:
        lines.append(secrets_exp)
        lines.append("")
    secrets_list: list = (findings.get("secrets") or {}).get("findings") or []
    if secrets_list:
        lines.append("| Type | Severity | File | Line | Description |")
        lines.append("|------|----------|------|------|-------------|")
        for item in secrets_list:
            t = str(item.get("type") or "")
            sev = str(item.get("severity") or "")
            f = str(item.get("file") or "")
            ln = str(item.get("line") or "")
            desc = str(item.get("detector") or item.get("description") or "").replace("|", "\\|")
            lines.append(f"| {t} | {sev} | {f} | {ln} | {desc} |")
    else:
        lines.append("No issues found in this category.")
    lines.append("")

    # 6b. Static Analysis / Semgrep
    lines.append("### Static Analysis / Semgrep\n")
    semgrep_exp = cat_exp.get("security") or ""
    if semgrep_exp:
        lines.append(semgrep_exp)
        lines.append("")
    semgrep_list: list = (findings.get("semgrep") or {}).get("findings") or []
    if semgrep_list:
        lines.append("| Rule ID | Severity | File | Line | Message |")
        lines.append("|---------|----------|------|------|---------|")
        for item in semgrep_list:
            rule_id = str(item.get("rule_id") or "")
            sev = str(item.get("severity") or "")
            f = str(item.get("file") or "")
            ln = str(item.get("line_start") or "")
            msg = str(item.get("message") or "").replace("|", "\\|")
            lines.append(f"| {rule_id} | {sev} | {f} | {ln} | {msg} |")
    else:
        lines.append("No issues found in this category.")
    lines.append("")

    # 6c. Python Security / Bandit
    lines.append("### Python Security / Bandit\n")
    bandit_exp = cat_exp.get("code_quality") or ""
    if bandit_exp:
        lines.append(bandit_exp)
        lines.append("")
    bandit_list: list = (findings.get("bandit") or {}).get("findings") or []
    if bandit_list:
        lines.append("| Test ID | Severity | File | Line | Issue |")
        lines.append("|---------|----------|------|------|-------|")
        for item in bandit_list:
            test_id = str(item.get("test_id") or "")
            sev = str(item.get("severity") or "")
            f = str(item.get("file") or "")
            ln = str(item.get("line") or "")
            issue = str(item.get("message") or item.get("issue_text") or "").replace("|", "\\|")
            lines.append(f"| {test_id} | {sev} | {f} | {ln} | {issue} |")
    else:
        lines.append("No issues found in this category.")
    lines.append("")

    # 6d. Dependency Vulnerabilities
    lines.append("### Dependency Vulnerabilities\n")
    deps_exp = cat_exp.get("dependencies") or ""
    if deps_exp:
        lines.append(deps_exp)
        lines.append("")
    deps_list: list = (findings.get("dependencies") or {}).get("findings") or []
    if deps_list:
        lines.append("| Package | Severity | CVE/ID | Description |")
        lines.append("|---------|----------|--------|-------------|")
        for item in deps_list:
            pkg = str(item.get("package") or "")
            sev = str(item.get("severity") or "")
            vuln_id = str(item.get("vulnerability_id") or "")
            desc = str(item.get("description") or "").replace("|", "\\|")
            lines.append(f"| {pkg} | {sev} | {vuln_id} | {desc} |")
    else:
        lines.append("No issues found in this category.")
    lines.append("")

    # 7. Positive Findings
    lines.append("## Positive Findings\n")
    if positive_findings:
        for finding in positive_findings:
            lines.append(f"- {finding}")
    else:
        lines.append("_No positive findings recorded._")
    lines.append("")

    # 8. Footer
    lines.append("---")
    lines.append(f"*{_FOOTER_TEXT}*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF generator
# ---------------------------------------------------------------------------

class _BreakMyAppPDF(FPDF):
    """Custom FPDF subclass with a branded header/footer on every page."""

    def header(self) -> None:
        # No per-page header — branding is in the title block.
        pass

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        # Left: report name
        self.cell(0, 6, "BreakMyApp Security Report", align="L")
        # Right: page number (overprint on same line)
        self.set_y(-12)
        self.cell(0, 6, f"Page {self.page_no()}", align="R")


def generate_pdf(scan: Any) -> bytes:
    """Return PDF bytes for a complete security report for *scan*."""

    findings: dict = (scan.findings or {}) if scan.findings is not None else {}
    ai: dict = findings.get("ai_explanation") or {}
    cat_exp: dict = ai.get("category_summaries") or {}
    top_priorities: list = ai.get("top_priorities") or []
    positive_findings: list = ai.get("positive_findings") or []

    score = scan.score
    score_str = f"{score}/100" if score is not None else "N/A"
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Colour constants
    _BLUE = (26, 86, 219)
    _DARK = (30, 30, 30)
    _GRAY = (100, 100, 100)
    _WHITE = (255, 255, 255)
    _ROW_ALT = (245, 245, 245)
    _HEADER_BG = (26, 86, 219)

    pdf = _BreakMyAppPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    usable_width = pdf.w - pdf.l_margin - pdf.r_margin  # ~180 mm

    # ------------------------------------------------------------------
    # Helper lambdas
    # ------------------------------------------------------------------

    def set_heading_style() -> None:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*_BLUE)

    def set_body_style() -> None:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_DARK)

    def set_small_gray() -> None:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_GRAY)

    def section_heading(text: str, top_gap: float = 6) -> None:
        pdf.ln(top_gap)
        set_heading_style()
        pdf.cell(0, 8, text, ln=True)
        # Underline rule
        pdf.set_draw_color(*_BLUE)
        pdf.set_line_width(0.3)
        y = pdf.get_y()
        pdf.line(pdf.l_margin, y, pdf.l_margin + usable_width, y)
        pdf.ln(2)
        set_body_style()

    def body_text(text: str, top_gap: float = 1) -> None:
        if not text:
            return
        set_body_style()
        pdf.ln(top_gap)
        pdf.multi_cell(0, 5, str(text))

    def draw_table(headers: list[str], col_widths: list[float], rows: list[list[str]]) -> None:
        """Draw a table with alternating row shading."""
        # Header row
        pdf.set_fill_color(*_HEADER_BG)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("Helvetica", "B", 9)
        for h, w in zip(headers, col_widths):
            pdf.cell(w, 7, h, border=0, fill=True, align="C")
        pdf.ln()

        # Data rows
        set_body_style()
        pdf.set_font("Helvetica", "", 8)
        for row_idx, row in enumerate(rows):
            if pdf.get_y() > pdf.h - 30:
                pdf.add_page()
            fill = row_idx % 2 == 1
            pdf.set_fill_color(*_ROW_ALT)
            pdf.set_text_color(*_DARK)
            for cell_val, w in zip(row, col_widths):
                pdf.cell(w, 6, str(cell_val), border=0, fill=fill, align="L")
            pdf.ln()
        pdf.ln(2)

    # ------------------------------------------------------------------
    # Title block
    # ------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 12, "BreakMyApp", ln=True, align="C")

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 8, "Security Report", ln=True, align="C")
    pdf.ln(4)

    # Metadata lines
    set_small_gray()
    pdf.cell(0, 6, f"Repository: {scan.repo_url or 'N/A'}", ln=True, align="C")
    pdf.cell(0, 6, f"Scan ID: {scan.id}", ln=True, align="C")
    pdf.cell(0, 6, f"Score: {score_str}  |  Status: {scan.status or 'N/A'}", ln=True, align="C")
    pdf.cell(0, 6, f"Generated: {generated_at}", ln=True, align="C")

    pdf.ln(4)
    pdf.set_draw_color(*_BLUE)
    pdf.set_line_width(0.5)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.l_margin + usable_width, y)
    pdf.ln(6)

    # ------------------------------------------------------------------
    # Score section (large centered)
    # ------------------------------------------------------------------
    section_heading("Production Readiness Score", top_gap=0)
    sc_color = _score_color(score)
    pdf.set_font("Helvetica", "B", 48)
    pdf.set_text_color(*sc_color)
    pdf.cell(0, 20, score_str, ln=True, align="C")
    body_text(ai.get("score_explanation") or "No score explanation available.")

    # ------------------------------------------------------------------
    # Executive Summary
    # ------------------------------------------------------------------
    section_heading("Executive Summary")
    body_text(ai.get("executive_summary") or "No executive summary available.")

    # ------------------------------------------------------------------
    # Top Priorities
    # ------------------------------------------------------------------
    section_heading("Top Priorities")
    if top_priorities:
        for i, priority in enumerate(top_priorities, 1):
            title = priority.get("title") or "Untitled"
            severity = (priority.get("severity") or "INFO").upper()
            description = priority.get("explanation") or ""
            recommendation = priority.get("action") or ""
            sev_color = _severity_color(severity)

            pdf.ln(2)
            # Numbered title
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_DARK)
            pdf.cell(6, 6, f"{i}.", align="R")
            # Severity badge inline
            pdf.set_text_color(*sev_color)
            pdf.cell(20, 6, f"[{severity}]", align="L")
            pdf.set_text_color(*_DARK)
            pdf.multi_cell(usable_width - 26, 6, title)

            if description:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 26)
                pdf.multi_cell(usable_width - 26, 5, description)

            if recommendation:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*_GRAY)
                pdf.set_x(pdf.l_margin + 26)
                pdf.multi_cell(usable_width - 26, 5, f"→ {recommendation}")
                pdf.set_text_color(*_DARK)
    else:
        body_text("No top priorities identified.")

    # ------------------------------------------------------------------
    # Findings by Category
    # ------------------------------------------------------------------
    section_heading("Findings by Category")

    # --- Secrets ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 7, "Secrets Detection", ln=True)
    body_text(cat_exp.get("secrets") or "")
    secrets_list: list = (findings.get("secrets") or {}).get("findings") or []
    if secrets_list:
        col_w = [30, 22, 55, 15, 58]
        headers = ["Type", "Severity", "File", "Line", "Description"]
        rows = [
            [
                _trunc(r.get("type") or "", 30),
                _trunc(r.get("severity") or "", 20),
                _trunc(r.get("file") or "", 60),
                str(r.get("line") or ""),
                _trunc(r.get("detector") or r.get("description") or "", 80),
            ]
            for r in secrets_list
        ]
        draw_table(headers, col_w, rows)
    else:
        body_text("No issues found in this category.")

    pdf.ln(3)

    # --- Semgrep ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 7, "Static Analysis / Semgrep", ln=True)
    body_text(cat_exp.get("security") or "")
    semgrep_list: list = (findings.get("semgrep") or {}).get("findings") or []
    if semgrep_list:
        col_w = [40, 22, 55, 15, 48]
        headers = ["Rule ID", "Severity", "File", "Line", "Message"]
        rows = [
            [
                _trunc(r.get("rule_id") or "", 40),
                _trunc(r.get("severity") or "", 20),
                _trunc(r.get("file") or "", 60),
                str(r.get("line_start") or ""),
                _trunc(r.get("message") or "", 80),
            ]
            for r in semgrep_list
        ]
        draw_table(headers, col_w, rows)
    else:
        body_text("No issues found in this category.")

    pdf.ln(3)

    # --- Bandit ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 7, "Python Security / Bandit", ln=True)
    body_text(cat_exp.get("code_quality") or "")
    bandit_list: list = (findings.get("bandit") or {}).get("findings") or []
    if bandit_list:
        col_w = [30, 22, 55, 15, 58]
        headers = ["Test ID", "Severity", "File", "Line", "Issue"]
        rows = [
            [
                _trunc(r.get("test_id") or "", 30),
                _trunc(r.get("severity") or "", 20),
                _trunc(r.get("file") or "", 60),
                str(r.get("line") or ""),
                _trunc(r.get("message") or r.get("issue_text") or "", 80),
            ]
            for r in bandit_list
        ]
        draw_table(headers, col_w, rows)
    else:
        body_text("No issues found in this category.")

    pdf.ln(3)

    # --- Dependencies ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 7, "Dependency Vulnerabilities", ln=True)
    body_text(cat_exp.get("dependencies") or "")
    deps_list: list = (findings.get("dependencies") or {}).get("findings") or []
    if deps_list:
        col_w = [35, 22, 40, 83]
        headers = ["Package", "Severity", "CVE/ID", "Description"]
        rows = [
            [
                _trunc(r.get("package") or "", 35),
                _trunc(r.get("severity") or "", 20),
                _trunc(r.get("vulnerability_id") or "", 40),
                _trunc(r.get("description") or "", 80),
            ]
            for r in deps_list
        ]
        draw_table(headers, col_w, rows)
    else:
        body_text("No issues found in this category.")

    # ------------------------------------------------------------------
    # Positive Findings
    # ------------------------------------------------------------------
    section_heading("Positive Findings")
    if positive_findings:
        set_body_style()
        for pf in positive_findings:
            pdf.set_x(pdf.l_margin + 4)
            pdf.multi_cell(usable_width - 4, 5, f"\u2022  {pf}")
    else:
        body_text("No positive findings recorded.")

    # ------------------------------------------------------------------
    # Footer branding line (last page)
    # ------------------------------------------------------------------
    pdf.ln(8)
    pdf.set_draw_color(*_GRAY)
    pdf.set_line_width(0.2)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.l_margin + usable_width, y)
    pdf.ln(3)
    set_small_gray()
    pdf.cell(0, 6, _FOOTER_TEXT, ln=True, align="C")

    # Return raw bytes
    return bytes(pdf.output())
